services:
  backend-server:
    image: cyberaware-api
    container_name: cyberaware-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env
    volumes:
      - .:/app