version: '3.8'

services:
  backend-server:
    image: cyberaware-api
    container_name: cyberaware-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app