# Generated by Django 5.2.4 on 2025-07-12 23:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_otp_expires_at_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 12, 23, 37, 22, 24323, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleprogress',
            unique_together={('user', 'module')},
        ),
    ]
