# Generated by Django 5.2.4 on 2025-07-12 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermoduleprogress',
            name='progress',
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 12, 23, 49, 5, 308231, tzinfo=datetime.timezone.utc)),
        ),
    ]
