# Generated by Django 5.2.4 on 2025-07-15 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_otp_expires_at_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 20, 44, 2, 387532, tzinfo=datetime.timezone.utc)),
        ),
    ]
