# Generated by Django 5.2.4 on 2025-07-17 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_otp_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='content',
        ),
        migrations.AddField(
            model_name='module',
            name='google_drive_file_id',
            field=models.CharField(default='1234567890', max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('text', 'Text')], default='video', max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 18, 48, 39, 734806, tzinfo=datetime.timezone.utc)),
        ),
    ]
