# Generated by Django 5.2.4 on 2025-07-17 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_module_content_module_google_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 19, 21, 45, 778710, tzinfo=datetime.timezone.utc)),
        ),
    ]
