# Generated by Django 5.2.4 on 2025-07-17 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_module_options_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 19, 23, 27, 182276, tzinfo=datetime.timezone.utc)),
        ),
    ]
