# Generated by Django 5.2.4 on 2025-07-17 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_module_updated_at_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 19, 31, 28, 95081, tzinfo=datetime.timezone.utc)),
        ),
    ]
