# Generated by Django 5.2.4 on 2025-08-21 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_module_updated_at_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='mux_asset_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='mux_playback_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='mux_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 21, 21, 34, 19, 473459, tzinfo=datetime.timezone.utc)),
        ),
    ]
